### ISSUE TITLE
Failing to build with MSVC 2017

### ISSUE THREAD

**Issue by motorsep** [eXistence/fhDOOM#17]
Fails to build: https://pastebin.com/aLSFHXq4

**Comment by revelator** [comment]
C++11 strikes again :P 
This is a common problem with sources from pre C++11 era, should be easy to fix.

**Comment by motorsep** [comment]
Well, I'm not a C++ programmer :( Otherwise I'd submit a fix already.

**Comment by revelator** [comment]
[narrowing-conversion.zip](https://github.com/eXistence/fhDOOM/files/2135260/narrowing-conversion.zip)

here you go.
apply with git's patcher.

**Comment by motorsep** [comment]
Thanks, that worked! However, still can't build on Windows :(

New issue: https://pastebin.com/aecDjxA5

**Comment by revelator** [comment]
the cmake problem seems to be that cmake's module for precompiled headers seems to make some rather bad assumptions when precompiled headers are enabled with msvc. 
We should probably use link time optimization instead untill they fix it ?. 

The undefined  function error comes from a function which no longer exists for the sound editor, removing it and all references fixes building but you still have to remove the offending precompile flags from fhDOOM.vcxproj. 

Hint they are all located in the resource compiler section.

I have it up and running on Doom3 but the ROE expansion crashes.

**Comment by eXistence** [comment]
I fixed the narrowing error with vs2017.
The other issue (RC1103: invalid option...) was related to cmake versions > 3.8 and has also been fixed.

**Comment by motorsep** [comment]
Still failing to build: https://pastebin.com/Hmtc8Cs5

11>Common.obj : error LNK2001: unresolved external symbol "void __cdecl EfxEditorInit(void)" (?EfxEditorInit@@YAXXZ)
11>D:\games\fhDOOM-master\build\msvc2017-x86\bin\RelWithDebInfo\fhDOOM.exe : fatal error LNK1120: 1 unresolved externals
11>Done building project "fhDOOM.vcxproj" -- FAILED.

**Comment by eXistence** [comment]
ooops, i should compile without Qt more often... 
should be fixed now. 
Sorry for the inconvenience :-)

**Comment by revelator** [comment]
You probably need to replace the glsl folder in pak100fhdoom.pk4 with the one in the base folder, if existence has made changes in any part of them rendering will as you say be fucked.

**Comment by revelator** [comment]
Also replace the guis and maps folder just to be sure.

**Comment by motorsep** [comment]
@revelator There is only one glsl/ folder and only one pak100fhdoom.pk4

I "installed" fhDoom as per instructions (although I didn't overwrite the existing packs, because who does that?!) and the copied over freshly built .exe and DLLs from master repo.

**Comment by revelator** [comment]
I ment open the pak100fhdoom.pk4 with 7zip or some other zip utility and replace the glsl maps and gui folders in there with the ones located in the base folder in the source folder :), the shaders might have been modified since its still under development so older shaders might cause some weird behaviour unless you replace them with the new ones.

I have it up and running here with no problems besides the expansion not working yet because of missing shaders. 

It's a little extra work but thats the price for testing out a build which has not yet been publicly released.
